/**
 * Client-side TTS utility — hybrid approach.
 *
 * 1. Voice Previews: Uses backend /api/tts/preview endpoint with the
 *    z-ai-web-dev-sdk TTS engine for accurate voice previews.
 * 2. Document Conversion: POST /api/tts/convert → single WAV file,
 *    generated by the server using English SDK voices (jam, kazi).
 *
 * Both previews and conversion use the same TTS engine on the server,
 * so what you hear in the preview matches the final output quality.
 */

import { getVoiceById } from './voices';
import { useAppStore } from './store';

// ═══════════════════════════════════════════════════════════════════
// PART 1: Voice Previews (Backend TTS API)
// ═══════════════════════════════════════════════════════════════════

let currentPreviewAudio: HTMLAudioElement | null = null;
let currentPreviewVoiceId: string | null = null;

/**
 * Play a voice preview using the backend TTS API.
 * Generates real TTS audio on the server and plays it back.
 */
export async function playVoicePreview(voiceId: string): Promise<void> {
  // Stop any current preview
  stopVoicePreview();

  const voiceProfile = getVoiceById(voiceId);
  if (!voiceProfile) {
    console.warn(`Voice profile not found: ${voiceId}`);
    return;
  }

  try {
    console.log(`[TTS Preview] Requesting preview for: ${voiceId} (sdkVoice: ${voiceProfile.sdkVoice})`);

    const response = await fetch('/api/tts/preview', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ voiceId }),
    });

    if (!response.ok) {
      let errorMessage = `Preview failed (HTTP ${response.status})`;
      try {
        const errorData = await response.json();
        errorMessage = errorData.error || errorMessage;
      } catch {
        // Response wasn't JSON
      }
      throw new Error(errorMessage);
    }

    const arrayBuffer = await response.arrayBuffer();
    const blob = new Blob([arrayBuffer], { type: 'audio/wav' });
    const audioUrl = URL.createObjectURL(blob);

    const audio = new Audio();
    currentPreviewAudio = audio;
    currentPreviewVoiceId = voiceId;

    return new Promise<void>((resolve, reject) => {
      audio.oncanplaythrough = () => {
        audio.play().catch((playErr) => {
          console.warn('[TTS Preview] Autoplay blocked:', playErr);
          // Don't reject — the audio is loaded, user can interact
          resolve();
        });
      };

      audio.onended = () => {
        currentPreviewVoiceId = null;
        URL.revokeObjectURL(audioUrl);
        resolve();
      };

      audio.onerror = () => {
        currentPreviewVoiceId = null;
        currentPreviewAudio = null;
        URL.revokeObjectURL(audioUrl);
        reject(new Error('Voice preview failed: audio playback error'));
      };

      audio.src = audioUrl;
      audio.load();
    });
  } catch (error) {
    currentPreviewVoiceId = null;
    currentPreviewAudio = null;
    console.error(`[TTS Preview] Error:`, error);
    throw error;
  }
}

/**
 * Stop the currently playing voice preview.
 */
export function stopVoicePreview(): void {
  if (currentPreviewAudio) {
    currentPreviewAudio.pause();
    currentPreviewAudio.currentTime = 0;
    currentPreviewAudio = null;
  }
  currentPreviewVoiceId = null;
}

/**
 * Check if a specific voice is currently playing its preview.
 */
export function isVoicePreviewPlaying(voiceId: string): boolean {
  return currentPreviewVoiceId === voiceId && currentPreviewAudio !== null && !currentPreviewAudio.paused;
}

/**
 * Check if TTS preview is available (always true with backend approach).
 */
export function isBrowserTTSAvailable(): boolean {
  return true;
}

// ═══════════════════════════════════════════════════════════════════
// PART 2: Document Conversion (backend-powered)
// ═══════════════════════════════════════════════════════════════════

export interface ConversionProgress {
  currentChunk: number;
  totalChunks: number;
  percent: number;
  status: 'preparing' | 'converting' | 'complete' | 'error';
  message: string;
  engine: 'server';
}

export interface ConversionResult {
  audioBlob: Blob;
  audioUrl: string;
  totalDuration: number;
  totalSize: number;
  engine: 'server';
}

/**
 * Convert text to audio using the backend TTS API.
 *
 * The server handles chunking, TTS generation, and proper WAV concatenation.
 * The client just receives the final audio file.
 */
export async function convertTextToAudio(
  text: string,
  voiceId: string,
  onProgress?: (progress: ConversionProgress) => void
): Promise<ConversionResult> {
  const voiceProfile = getVoiceById(voiceId);
  if (!voiceProfile) {
    throw new Error(`Voice profile not found: ${voiceId}`);
  }

  if (!text || text.trim().length === 0) {
    throw new Error('No text content to convert to audio');
  }

  onProgress?.({
    currentChunk: 0,
    totalChunks: 1,
    percent: 10,
    status: 'preparing',
    message: 'Sending text to server for conversion...',
    engine: 'server',
  });

  try {
    console.log(`[TTS Convert] Starting conversion: ${text.length} chars, voiceId: ${voiceId} (${voiceProfile.sdkVoice}, speed: ${voiceProfile.ttsSpeed}, pitchShift: ${voiceProfile.pitchShift})`);

    // Include user role header if authenticated (session cookie is sent automatically)
    const { user } = useAppStore.getState();
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (user?.role) {
      headers['X-User-Role'] = user.role;
    }

    const response = await fetch('/api/tts/convert', {
      method: 'POST',
      headers,
      credentials: 'include',
      body: JSON.stringify({
        text: text.trim(),
        voiceId,
      }),
    });

    if (!response.ok) {
      let errorMessage = `Conversion failed (HTTP ${response.status})`;
      try {
        const errorData = await response.json();
        errorMessage = errorData.error || errorMessage;
      } catch {
        // Response wasn't JSON — use default error message
      }
      throw new Error(errorMessage);
    }

    onProgress?.({
      currentChunk: 1,
      totalChunks: 1,
      percent: 90,
      status: 'converting',
      message: 'Receiving audio from server...',
      engine: 'server',
    });

    // Create a properly-typed blob
    const arrayBuffer = await response.arrayBuffer();
    const blob = new Blob([arrayBuffer], { type: 'audio/wav' });
    const audioUrl = URL.createObjectURL(blob);

    console.log(`[TTS Convert] Received audio: ${blob.size} bytes`);

    // Estimate duration: output is always 24000 Hz, 16-bit mono (proper resampling)
    // Pitch shifting now uses resampling which adds more samples but keeps 24000 Hz
    const bytesPerSecond = 24000 * 2; // 16-bit mono = 2 bytes per sample at 24kHz
    const estimatedDurationSeconds = (blob.size - 44) / bytesPerSecond; // subtract WAV header

    onProgress?.({
      currentChunk: 1,
      totalChunks: 1,
      percent: 100,
      status: 'complete',
      message: 'Conversion complete!',
      engine: 'server',
    });

    return {
      audioBlob: blob,
      audioUrl,
      totalDuration: Math.round(estimatedDurationSeconds * 100) / 100,
      totalSize: blob.size,
      engine: 'server',
    };
  } catch (error) {
    onProgress?.({
      currentChunk: 0,
      totalChunks: 1,
      percent: 0,
      status: 'error',
      message: error instanceof Error ? error.message : 'Conversion failed',
      engine: 'server',
    });
    throw error;
  }
}

// ═══════════════════════════════════════════════════════════════════
// PART 3: Utility functions
// ═══════════════════════════════════════════════════════════════════

/**
 * Download an audio blob as a file.
 */
export function downloadAudioBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const ext = blob.type.includes('wav') ? '.wav' : blob.type.includes('webm') ? '.webm' : '.mp3';
  a.download = filename.endsWith(ext) ? filename : `${filename}${ext}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

/**
 * Clean up an object URL created for audio playback.
 */
export function revokeAudioUrl(url: string): void {
  try {
    URL.revokeObjectURL(url);
  } catch {
    // Ignore
  }
}
